apiVersion: v1
entries:
  rabbitmq:
  - apiVersion: v1
    appVersion: 3.8.0
    created: "2020-05-25T17:38:16.944607+05:30"
    description: rabbitmq Deployment chart
    digest: 72d1afc210e846e26be0668fc029d8109125b876434b5625576cd67daa110a19
    keywords:
    - rabbitmq
    - amqp
    - Kubernetes
    name: rabbitmq
    urls:
    - rabbitmq-1.0.0.tgz
    version: 1.0.0
generated: "2020-05-25T17:38:16.943761+05:30"
