apiVersion: v1
entries:
  rabbitmq:
  - apiVersion: v1
    appVersion: 3.8.0
    created: "2020-05-24T18:34:06.866848+05:30"
    description: rabbitmq Deployment chart
    digest: ae13c782debfc1424818e212ed6de77d9472afabf875efe667143e1a5dc78970
    keywords:
    - rabbitmq
    - amqp
    - Kubernetes
    name: rabbitmq
    urls:
    - rabbitmq-1.0.0.tgz
    version: 1.0.0
generated: "2020-05-24T18:34:06.866059+05:30"
