apiVersion: v1
entries:
  rabbitmq:
  - apiVersion: v1
    appVersion: 3.8.0
    created: "2020-05-25T17:32:28.272044+05:30"
    description: rabbitmq Deployment chart
    digest: edffdec79e886dc21daf1653f606b8b4d5f058f01e96059ae24d9f308132a6b5
    keywords:
    - rabbitmq
    - amqp
    - Kubernetes
    name: rabbitmq
    urls:
    - rabbitmq-1.0.0.tgz
    version: 1.0.0
generated: "2020-05-25T17:32:28.269959+05:30"
