apiVersion: v1
kind: Secret
metadata:
  name: {{ include "rabbitmq.fullname" . }}-secret
  labels:
{{ include "labels.standard" . | indent 4 }}
type: Opaque
data:
  RABBITMQ_DEFAULT_USER: {{ .Values.rabbitmq.username | b64enc | quote }}
  RABBITMQ_DEFAULT_PASS: {{ .Values.rabbitmq.password | b64enc | quote }}
  RABBITMQ_ERLANG_COOKIE: {{ .Values.rabbitmq.erlangCookie | b64enc | quote }}
  {{- if .Values.tls.enabled }}
  RABBITMQ_SSL_CERT_FILE: /opt/rabbitmq/certs/server_certificate.pem
  RABBITMQ_SSL_KEY_FILE: /opt/rabbitmq/certs/private_key.pem
  RABBITMQ_SSL_CA_FILE: /opt/rabbitmq/certs/ca_certificate.pem
  {{- end }}