apiVersion: v1
kind: Service
metadata:
  name: {{ include "rabbitmq.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: amqp
      port: {{ .Values.service.port }}
      targetPort: amqp
  selector:
{{ include "labels.standard" . | indent 4 }
