apiVersion: v1
kind: Service
metadata:
  name: {{ include "rabbitmq.fullname" . }}
  labels:
{{ include "labels.standard" . | indent 4 }}
{{- if .Values.service.annotations }}
  annotations:
{{ toYaml .Values.service.annotations | indent 4 }}
{{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: amqp
      port: {{ .Values.service.port }}
      targetPort: amqp
    - name: management
      port: {{ .Values.service.managementPort }}
      targetPort: management
  selector:
{{ include "labels.standard" . | indent 4 }
