apiVersion: v1
kind: Service
metadata:
  name: {{ include "rabbitmq.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: amqp
      port: 8080
      targetPort: amqp
  selector:
    app: test
