apiVersion: v1
kind: Service
metadata:
  name: {{ include "mychart.fullname" . }}
  labels:
{{ include "labels.standard" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 2375
      protocol: TCP
      name: mychartport
  selector:
    app: {{ include "mychart.name" . }}
    release: {{ .Release.Name }}