apiVersion: v1
kind: Service
metadata:
  name: {{ include "rabbitmq.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: amqp
      port: {{ .Values.service.port }}
      targetPort: amqp
    - name: management
      port: {{ .Values.service.managementPort }}
      targetPort: management
    {{- if .Values.rabbitmq.tls.enabled }}
    - name: amqp-ssl
      port: {{ .Values.service.tlsPort }}
      targetPort: amqp-ssl
    - name: management-ssl
      port: {{ .Values.service.tlsmanagementPort }}
      targetPort: management-ssl
    {{- end }}
  selector:
    name: test
