apiVersion: v1
kind: Service
metadata:
  name: {{ template "rabbitmq.fullname" . }}
  labels:
{{- if .Values.service.labels }}
{{- toYaml .Values.service.labels | indent 4 }}
{{- end }}
{{- if .Values.service.annotations }}
  annotations:
{{ toYaml .Values.service.annotations | indent 4 }}
{{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: amqp
      port: {{ .Values.service.port }}
      targetPort: amqp
    - name: management
      port: {{ .Values.service.managementPort }}
      targetPort: management
    {{- if .Values.rabbitmq.tls.enabled }}
    - name: amqp-ssl
      port: {{ .Values.service.tlsPort }}
      targetPort: amqp-ssl
    - name: management-ssl
      port: {{ .Values.service.tlsmanagementPort }}
      targetPort: management-ssl
    {{- end }}
  selector:
    app: {{ template "rabbitmq.name" . }}
    release: "{{ .Release.Name }}"
